version: "3.7"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: ./app
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
      PORT: 4000
    volumes:
      - ./app/notes:/opt/notes-app/notes
      - ./app/public:/opt/notes-app/public
      - ./app/scripts:/opt/notes-app/scripts
      - ./app/server:/opt/notes-app/server
      - ./app/src:/opt/notes-app/src
      - ./app/credentials.js:/opt/notes-app/credentials.js

volumes:
  db:
